apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-app
  namespace: argocd
spec:
  project: default
  source:
    path: knative
    repoURL: https://github.com/lolgab/knative-cluster.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: knative
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
